---
- name: configuring web server
  hosts: web
  tasks:
    - name: install webserver
      dnf:
        name: httpd
        state: installed
    - name: start & enable service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: copy index.html
      copy:
        src: /root/index.html
        dest: /var/www/html/index.html
